export const classes = [
  {
    id: 1,
    title: "Language & Speaking",
    subtitle: "",
    image: "/speak.jpg",
    age: "1 - 4 years",
    time: "7 - 8 AM",
    capacity: "20 Kids",
    duration: 0.15,
  },
  {
    id: 2,
    title: "Art & Drawing",
    subtitle: "",
    image: "/art-color.jpg",
    age: "1 - 4 years",
    time: "8 - 9 AM",
    capacity: "20 Kids",
    duration: 0.35,
  },
  {
    id: 3,
    title: "Color Management",
    subtitle: "",
    image: "/color-management.jpg",
    age: "1 - 4 years",
    time: "9 - 10 AM",
    capacity: "20 Kids",
    duration: 0.55,
  },
  {
    id: 4,
    title: "General Knowledge",
    subtitle: "",
    image: "/knowledge.jpg",
    age: "2 - 4 years",
    time: "11 - 12 AM",
    capacity: "20 Kids",
    duration: 0.15,
  },
  {
    id: 5,
    title: "Athletic & Dance",
    subtitle: "",
    image: "/dance.webp",
    age: "2 - 4 years",
    time: "1 - 2 PM",
    capacity: "20 Kids",
    duration: 0.35,
  },
  {
    id: 6,
    title: "History",
    subtitle: "",
    image: "/history-learning.jpg",
    age: "2 - 4 years",
    time: "2 - 3 PM",
    capacity: "20 Kids",
    duration: 0.55,
  },
];
