export const classes = [
  {
    id: 1,
    title: "Language & Speaking",
    subtitle: "",
    image: "/study.jpg",
    age: "3-5 years",
    time: "3-4 AM",
    capacity: "20 Kids",
    duration: 0.15,
  },
  {
    id: 2,
    title: "Art & Drawing",
    subtitle: "",
    image: "/drawing.jpg",
    age: "3-5 years",
    time: "3-4 AM",
    capacity: "20 Kids",
    duration: 0.35,
  },
  {
    id: 3,
    title: "Color Management",
    subtitle: "",
    image: "/color.jpg",
    age: "3-5 years",
    time: "3-4 AM",
    capacity: "20 Kids",
    duration: 0.55,
  },
  {
    id: 4,
    title: "General Knowledge",
    subtitle: "",
    image: "/general.jpg",
    age: "3-5 years",
    time: "3-4 AM",
    capacity: "20 Kids",
    duration: 0.15,
  },
  {
    id: 5,
    title: "Athletic & Dance",
    subtitle: "",
    image: "/athletic.jpg",
    age: "3-5 years",
    time: "3-4 AM",
    capacity: "20 Kids",
    duration: 0.35,
  },
  {
    id: 6,
    title: "History",
    subtitle: "",
    image: "/history.jpg",
    age: "3-5 years",
    time: "3-4 AM",
    capacity: "20 Kids",
    duration: 0.55,
  },
];
